# 開發環境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_dashboard?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Taipei
    username: root
    password: soso0301
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: simple

logging:
  level:
    com.crypto.dashboard: DEBUG
coingecko:
  api:
    key: CG-vczvnvBTsqG7Z8EVB7KRb3ii

jwt:
  secret: coinvue-secret-key-minimum-32-characters-required-for-hs512
  expiration: 86400000

